__version__ = "1.10.0"

WANDB_PROJECT = "taomap"
ORIGIN_TERM_BLOCK = 0
BLOCKS_PER_TERM = 400
BLOCKS_SHARE_SEED = 10
BLOCKS_START_BENCHMARK = 20
BLOCKS_PER_GROUP = 5
BLOCKS_SEEDHASH_START = 150
BLOCKS_SEEDHASH_END = 200

# BLOCKS_PER_TERM = 20
# BLOCKS_SHARE_SEED = 2
# BLOCKS_START_BENCHMARK = 4
# BLOCKS_PER_GROUP = 1
# BLOCKS_SEEDHASH_START = 16
# BLOCKS_SEEDHASH_END = 18

BENCHMARK_SHAPE = (50, 1024, 1024)

# VALIDATOR_MIN_STAKE = 5000
VALIDATOR_MIN_STAKE = 10
